name: Pasa tests de cobertura
on: [push]

jobs:
  build:
    name: Cobertura
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Instalación general
        run: npm ci
      - name: Ejecuta tests de cobertura
        run: npm run coverage
      - name: Crea los informes
        run: npm run coverage-reports
